# Generated by Django 5.0.6 on 2024-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='nome',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
