# Generated by Django 5.0.6 on 2024-05-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0003_bairros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('cnpj', models.DecimalField(decimal_places=0, max_digits=14)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bairros',
            new_name='Combos',
        ),
        migrations.DeleteModel(
            name='Nome',
        ),
    ]
