# Generated by Django 5.0.6 on 2024-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0004_empresas_rename_bairros_combos_delete_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('velocidade', models.CharField(max_length=100)),
                ('observacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Combos',
        ),
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Provedor',
        ),
        migrations.AddField(
            model_name='planos',
            name='provedor',
            field=models.ManyToManyField(to='postgresql.provedor'),
        ),
    ]
