# Generated by Django 5.0.6 on 2024-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0006_planos_fibra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='provedor',
        ),
        migrations.AddField(
            model_name='provedor',
            name='planos',
            field=models.ManyToManyField(to='postgresql.planos'),
        ),
    ]
