# Generated by Django 5.0.6 on 2024-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0007_remove_planos_provedor_provedor_planos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='velocidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
