# Generated by Django 5.0.6 on 2024-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0008_alter_planos_velocidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='velocidade',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
