# Generated by Django 5.0.6 on 2024-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0009_alter_planos_velocidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='url',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
