# Generated by Django 5.0.6 on 2024-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0011_alter_provedor_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provedor',
            name='url',
        ),
        migrations.AddField(
            model_name='planos',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
