# Generated by Django 5.0.6 on 2024-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0012_remove_provedor_url_planos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='apelido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
