# Generated by Django 5.0.6 on 2024-05-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0013_planos_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='satelite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
